### PR TITLE
Make ortools dependency optional

### PR DESCRIPTION
**Pull request by nhuet**
We want the library to work without ortools as long as we do not use the functions using it.

### CODE REVIEW

**Comment by nhuet** [comment]
Perhaps we want to have a warning when the module decomon/numpy/milp/activation.py is imported without ortools being installed ? Or just have an explanation in docs about when and why ortools is needed ?

**Comment by ducoffeM** [comment]
We could use a tag and when specific functions are use (boud_A, bound_B with solver=ORTOOLS) raise an ImportError ?

**Comment by nhuet** [comment]
Ok for the error. 
I do not understand what you mean by a tag. Do you mean to be able to install ortools with
`pip install decomon[supertagname]` ?

**Comment by nhuet** [comment]
Ideally we would like also a test with these functions. 
Then we could check 
- in an environment without ortools, that the error is raised
- in an environment with ortools, that the functions work as expected

**Pull request merged**
